### ISSUE TITLE
Documentation Needs An Update - Include Dependencies

### ISSUE THREAD

**Issue by JeffHochberg** [OpenRTX/dmrconfig#45]
Hello,

Thanks for your contribution to the DMR community!

I've been reading through some of the other issues and there seem to be a few people having issues that are all related to not having dependencies installed.

If you add the list of required packages to your documentation, that would go a long way towards helping people be successful with compiling and installing from source.

pkg-config
libusb-1.0-0-dev
libudev-dev

sudo apt install pkg-config libusb-1.0-0-dev libudev-dev -y

That would take care of the dependencies for Ubuntu Linux. I'm running 18.04 LTS here. There are probably other dependencies but I'm working from a computer that I used for compiling other applications, so I already had them installed.

I find it's always best to build a VM with a fresh installation of Linux, then document every package that you have to install in order to be able to compile successfully, that way, others will know they have what they need.

Hopefully, that's helpful to you and others! Thanks again!!!

-JeffH

Jeff Hochberg
W4JEW
Atlanta, GA

**Comment by user111222333** [comment]
To help other users of GNU/Linux Debian 10 (Buster) OS and it's derivatives...

#----------------------------------
1. Before installing on Debian.

Install following dependencies.

Elevate your OS log-in privileges to a super-user root or run commands with sudo:

# apt install pkg-config libusb-1.0-0-dev libudev-dev

Once these packages - dependencies are installed on the system, now you can go ahead with instructions provided how to compile using a 'make' file.

Note: above dependencies are all included in default Debian repositories and apt or apt-get package manager is aware of those packages. 


#----------------------------------
2. Use git to clone to your local HDD and build your dmrconfig:

Install git and clone dmrconfig from git to convenient location on your file system.

# apt update && apt install git

From there just follow the instructions provided in documentation for dmrconfig.

Move in to directory where you got-cloned dmrconfig files:
# cd /home/user-X/dmrconfig/

Now run make file:

# make

Followed by:

# make install

That's it. Now you can call dmrconfig as any regular program and read, edit and write your codeplug file in to your USB connected radio.

Make sure to create a dedicated USB rules file to be able to allow dmrconfig to communicate with usb connected radio with out elevating your privileges to a super user. 

This is tested and confirmed to work as expected on GNU/Linux Debian Buster (10)

Damien

**Comment by cyberjew** [comment]
@user111222333 VERY NICE! Thanks for adding the additional detail.

@sergev please merge these instructions into your documentation/wiki.

**Comment by fmarier** [comment]
@user111222333 By the way, if you are using buster, you might be able to use the [bullseye package](https://packages.debian.org/bullseye/dmrconfig), though I haven't tested this.

**Comment by user111222333** [comment]
Thank you Mr. Marier for your response.
This is awesome news! I can't wait for 'dmrconfig' to be reviewed and accepted in to debian repository.
I feel like this is a cause for a celebration, at least personally for me.
I use a DMR radio and Debian is the only OS I trust my computing to.
Your efforts in developing 'dmrconfig' is literally a life line to users like me.
It was important for me to let you know this.
Thank you.

PS:
I found what might be a bug, and opened a request on github. Do you know if anyone on a dev team of 'dmrconfig' might be able to consider reviewing it?

Damien

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by fmarier** [comment]
@user111222333 If you find a bug in the Debian package, you can file a bug on the Debian bug tracker: https://bugs.debian.org/cgi-bin/pkgreport.cgi?archive=0;dist=unstable;ordering=normal;repeatmerged=0;src=dmrconfig

**Comment by Nimayer** [comment]
The README.md has been updated with build instructions and dependencies.
