### ISSUE TITLE
Contactlist Anytone 878: Too many contacts!

### ISSUE THREAD

**Issue by Kreischie** [OpenRTX/dmrconfig#50]
Yesterday i noticed that i can't write my new contactlist to my 878. It says too many contacts. But the radio can take 200.000 contacts and the file has about 160.000 contacts. In CPS i can write it without any problems.

![ss+(2020-04-12+at+10 11 04)](https://user-images.githubusercontent.com/45562553/79064112-76563d00-7ca6-11ea-8a37-3bdb23b1af3d.png)

This list:
https://raw.githubusercontent.com/ContactLists/ContactLists/master/Anytone/578_8x8_WW_default.csv

v1.1

**Comment by Eszartek** [comment]
I see that uv686.c has :

`#define NCALLSIGNS      160000`

My guess would be changing that to 200000 would do the trick. The 160k number was from an earlier revision of firmware.

**Comment by Eszartek** [comment]
I tried to upload your contacts csv file to my radio. got the same error:
```$ ./dmrconfig -u 578_8x8_WW_default.csv 
Serial port: /dev/ttyACM3
Connect to Anytone AT-D878UV.
Read file '578_8x8_WW_default.csv'.
WARNING: Too many callsigns!
Skipping the rest.
Total 160000 contacts, 8089006 bytes.
Write: ##^C
```
Then I changed d868uv.c line 46 to
` #define NCALLSIGNS 200000 `
and line 472 to 
` if (addr >= 0x02680000 && addr < 0x0298d40) {`
then recompiled.

Now it succeeds:
```./dmrconfig -u 578_8x8_WW_default.csv 
Serial port: /dev/ttyACM3
Connect to Anytone AT-D878UV.
Read file '578_8x8_WW_default.csv'.
Total 160758 contacts, 8129740 bytes.
Write: ############################################################################################## done.
Close device.

```
Now to test to see if it really worked without any side effects. So far, when I tested a parrot call to my own hblink server, it came back with my id, callsign etc.

**Comment by fmarier** [comment]
The callsign limits were raised in [firmware 1.35/2.35](https://cdn.shopify.com/s/files/1/0833/9095/files/D868UV_V2.35_official_190620.zip?625) for the AnyTone D868UV:

> V1.35 and V2.35 Improvements (dated 2019-6-20)
> 3. Increase the digital contact to 200,000 contacts.

and in [firmware 1.13](https://cdn.shopify.com/s/files/1/0833/9095/files/D878UV_V1.13_Official_release.zip?594) for the AnyTone D878UV:

> D878UV firmware update V1.13 (dated 2019-6-8)
> Change List
> 1.Increased to 200,000 digital contacts.

**Comment by fmarier** [comment]
Noting that the full [RadioID.net userid dump](https://database.radioid.net/database/dumps#!) (`user.csv`) is now over 160k entries. 167890 callsigns as of 2020-07-19.
